---
title: "da420_PROJECT2_GRAHN"
author: "Jason Grahn"
date: "1/17/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

Download Dodger.csv
```{r}
dodgers <- read_csv("dodgers.csv", 
                    col_types = cols(month = col_factor(levels = c("JAN", "FEB", "MAR", "APR",
                                                                   "MAY", "JUN", "JUL", "AUG",
                                                                   "SEP", "OCT", "NOV", "DEC"))))
glimpse(dodgers)
```

use R to develop two side-by-side boxplots, as seen in Figure 2.1 and Figure 2.2
```{r}
#need to transform full name days to abbreviated; ie "monday" to "mon"
#and turn that, and day/night into factors.
dodgers <- dodgers %>% mutate("Attend/1000" = attend/1000,
                              day_of_week = case_when(day_of_week == "Monday" ~ "Mon",
                                 day_of_week == "Tuesday" ~ "Tue",
                                 day_of_week == "Wednesday" ~ "Wed",
                                 day_of_week == "Thursday" ~ "Thur",
                                 day_of_week == "Friday" ~ "Fri",
                                 day_of_week == "Saturday" ~ "Sat",
                                 day_of_week == "Sunday" ~ "Sun"),
                              #and need to assign them factor levels
                              day_of_week_f = factor(day_of_week, levels = c("Mon", "Tue", "Wed",
                                                                           "Thur", "Fri", "Sat", "Sun")),
                              day_night_f = factor(day_night, levels = c("Night", "Day")))

# boxplots with ggplot using the dodger data
## day of week on X
## attendence in K's on Y
dow_box <- dodgers %>% 
  ggplot(aes(x = day_of_week_f, y = (attend/1000))) +
  geom_boxplot(fill = "pink") +
  theme_light() +
  theme(legend.position="none") +
  labs(y = "Attendence (1000)",
       x = "Day of the Week")
## month on X
## attendence in K's on Y
mon_box <- dodgers %>% 
  ggplot(aes(x = month, y = (attend/1000))) +
  geom_boxplot(fill = "dodgerblue1") +
  theme_light() +
  theme(legend.position="none") +
  labs(y = "", x = "Month of Year")

#put these side by side
cowplot::plot_grid(dow_box, mon_box)
```

and two scatter plots, as seen in Figure 2.3 
```{r}
#we're analyzing days with fireworks against day / night, clear / cloudy, AND temperature
#fireworks by shape and color
#attendence (K's) on Y
#temp on X
dodgers %>% 
  ggplot(aes(x = temp, 
             y = attend/1000,
             shape = fireworks,
             color = fireworks)) +
  geom_point() +
  theme_bw() +
  theme(legend.position="top") +
  labs(y = "Attendence (thousands)",
       x = "Temperature (Degrees Fahrenheit)") +
  facet_wrap(day_night_f ~ skies)
```

and Figure 2.4
```{r}
# scatterplot teams against attendence 
# y axis is opposing teams
# x axis is attendence (K's)
# fill by day/night
dodgers %>% 
  ggplot(aes(x = (attend/1000), y = opponent)) + 
  geom_point(aes(color = day_night)) +
  theme_bw() +
  theme(legend.position="top") +
  labs(y = "",
       x = "Attendence (thousands)")
```

Use R to develop a Regression Model Performance, as seen in Figure 2.5. Examine regression diagnostics for the fitted model. Hint: Look at the Exhibit 2.1 in page 25-27.
```{r}
#prediction will predict attendence based on bobbleheads
#using actual attendence
#with a test and a train set

# Predictive Model for Los Angeles Dodgers Promotion and Attendance (R)
library(car)   # special functions for linear regression
library(lattice)   # graphics package

# employ training-and-test regimen for model validation
set.seed(42) # set seed for repeatability of training-and-test split

training_test <- c(rep(1,length=trunc((2/3)*nrow(dodgers))),
                   rep(2,length=(nrow(dodgers) - trunc((2/3)*nrow(dodgers)))))
dodgers$training_test <- sample(training_test) # random permutation
dodgers$training_test <- factor(dodgers$training_test,
  levels=c(1,2), labels=c("TRAIN","TEST"))

dodgers.train <- subset(dodgers, training_test == "TRAIN")
print(str(dodgers.train)) # check training data frame
dodgers.test <- subset(dodgers, training_test == "TEST")
print(str(dodgers.test)) # check test data frame
 # specify a simple model with bobblehead entered last

my.model <- {attend ~ ordered_month + ordered_day_of_week + bobblehead}
# fit the model to the training set
train.model.fit <- lm(my.model, data = dodgers.train)
# summary of model fit to the training set
print(summary(train.model.fit))
# training set predictions from the model fit to the training set
dodgers.train$predict_attend <- predict(train.model.fit)
# test set predictions from the model fit to the training set
dodgers.test$predict_attend <- predict(train.model.fit,
  newdata = dodgers.test)
# compute the proportion of response variance
# accounted for when predicting out-of-sample
cat("\n","Proportion of Test Set Variance Accounted for: ",
round((with(dodgers.test,cor(attend,predict_attend)^2)),
  digits=3),"\n",sep="")
# merge the training and test sets for plotting
dodgers.plotting.frame <- rbind(dodgers.train,dodgers.test)
 # generate predictive modeling visual for management
group.labels <- c("No Bobbleheads","Bobbleheads")

group.symbols <- c(21,24)
group.colors <- c("black","black")
group.fill <- c("black","red")
xyplot(predict_attend/1000 ~ attend/1000 | training_test,
       data = dodgers.plotting.frame, groups = bobblehead, cex = 2,
       pch = group.symbols, col = group.colors, fill = group.fill,
       layout = c(2, 1), xlim = c(20,65), ylim = c(20,65),
       aspect=1, type = c("p","g"),
       panel=function(x,y, ...)
            {panel.xyplot(x,y,...)
             panel.segments(25,25,60,60,col="black",cex=2)
            },
       strip=function(...) strip.default(..., style=1),
       xlab = "Actual Attendance (thousands)",
       ylab = "Predicted Attendance (thousands)",
       key = list(space = "top",
              text = list(rev(group.labels),col = rev(group.colors)),
              points = list(pch = rev(group.symbols),
              col = rev(group.colors),
              fill = rev(group.fill))))
# use the full data set to obtain an estimate of the increase in
# attendance due to bobbleheads, controlling for other factors
my.model.fit <- lm(my.model, data = dodgers)

# use all available data
print(summary(my.model.fit))
# tests statistical significance of the bobblehead promotion
# type I anova computes sums of squares for sequential tests
print(anova(my.model.fit))
cat("\n","Estimated Effect of Bobblehead Promotion on Attendance: ",
round(my.model.fit$coefficients[length(my.model.fit$coefficients)],
digits = 0),"\n",sep="")
# standard graphics provide diagnostic plots
plot(my.model.fit)
# additional model diagnostics drawn from the car package
library(car)
residualPlots(my.model.fit)
marginalModelPlots(my.model.fit)
print(outlierTest(my.model.fit))

```
