---
title: "project07"
author: "Jason Grahn"
date: "2/18/2019"
output: word_document
---

```{r load packages, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(twitteR)
library(sentiment)
library(plyr)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
library(rstudioapi)
```

```{r keys to the car, message=FALSE, warning=FALSE}
# trying to set up code externalization https://yihui.name/knitr/demo/externalization/
# Because embedding passwords in side a script is a horrid horrid practice.
api_key <- ""

api_secret <- ""

token <- ""

token_secret <- ""
```


```{r this should be secure}
setup_twitter_oauth(api_key, #api key
                    api_secret,
                    token,
                    token_secret)
```

```{r harvest some tweets}
some_tweets <- searchTwitter("starbucks", 
                             n=2000, 
                             lang="en")
# get the text
some_txt <- sapply(some_tweets, function(x) x$getText())
```

```{r write some_tweets to rdata, eval=FALSE, include=FALSE}
#save(some_tweets, file=here::here("project07/some_tweets.Rdata"))
```


```{r}
# remove retweet entities
some_txt <- gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", some_txt)
# remove at people
some_txt <- gsub("@\\w+", "", some_txt)
# remove punctuation
some_txt <- gsub("[[:punct:]]", "", some_txt)
# remove numbers
some_txt <- gsub("[[:digit:]]", "", some_txt)
# remove html links
some_txt <- gsub("http\\w+", "", some_txt)
# remove unnecessary spaces
some_txt <- gsub("[ \t]{2,}", "", some_txt)
some_txt <- gsub("^\\s+|\\s+$", "", some_txt)
```

```{r}
# define "tolower error handling" function
try.error = function(x)
  {
  # create missing value
  y = NA
  # tryCatch error
  try_error = tryCatch(tolower(x), error=function(e) e)
  # if not an error
  if (!inherits(try_error, "error"))
    y = tolower(x)
  # result
  return(y)
}
  
# lower case using try.error with sapply
some_txt <- sapply(some_txt, try.error)
  
# remove NAs in some_txt
some_txt <- some_txt[!is.na(some_txt)]

names(some_txt) = NULL
```


```{r}
# classify emotion
class_emo <- classify_emotion(some_txt, algorithm="bayes", prior=1.0)

# get emotion best fit
emotion <- class_emo[,7]

# substitute NA's by "unknown"
emotion[is.na(emotion)] = "unknown"

# classify polarity
class_pol <- classify_polarity(some_txt, algorithm="bayes")

# get polarity best fit
polarity <- class_pol[,4]
```

```{r}
# data frame with results
sent_df <- data.frame(text = some_txt, 
                      emotion = emotion,
                      polarity = polarity, 
                      stringsAsFactors=FALSE)

# sort data frame
sent_df = within(sent_df,
                 emotion <- factor(emotion, 
                                   levels=names(sort(table(emotion),
                                                     decreasing=TRUE))))
```

```{r}
# plot distribution of emotions
emotions <- ggplot(sent_df, aes(x=emotion)) +
  geom_bar(aes(y=..count.., fill=emotion)) +
  scale_fill_brewer(palette="Dark2") +
  labs(x="emotion categories", 
       y="number of tweets",
       title = "Sentiment Analysis of Tweets about Starbucks",
       subtitle = "classification by emotion") +
  theme(legend.position = "none") +
  coord_flip()

# plot distribution of polarity
polarities <- ggplot(sent_df, aes(x=polarity)) +
  geom_bar(aes(y=..count.., fill=polarity)) +
  scale_fill_brewer(palette="RdGy") +
  labs(x="polarity categories", 
       y="number of tweets",
       title = "Sentiment Analysis of Tweets about Starbucks",
       subtitle = "classification by polarity") +
  theme(legend.position = "none")

cowplot::plot_grid(emotions, polarities)
```

```{r}
# separating text by emotion
emos = levels(factor(sent_df$emotion))
nemo = length(emos)
emo.docs = rep("", nemo)
for (i in 1:nemo)
  {
  tmp = some_txt[emotion == emos[i]]
  emo.docs[i] = paste(tmp, collapse=" ")
  }

# remove stopwords
emo.docs = removeWords(emo.docs, stopwords("english"))

# create corpus
corpus = Corpus(VectorSource(emo.docs))
tdm = TermDocumentMatrix(corpus)
tdm = as.matrix(tdm)
colnames(tdm) = emos
```

```{r}
# comparison word cloud
comparison.cloud(tdm, 
                 colors = brewer.pal(nemo, "Dark2"),
                 scale = c(3,.25), 
                 random.order = FALSE, 
                 title.size = 1.5)
```



