---
title: "project08"
author: "Jason Grahn"
date: "2/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(aod) 
library(ggplot2) 
library(Rcpp)
```


```{r}
library(readr)
mydata <- read_csv(here::here("project08/binary.csv"))
```

```{r}
summary(mydata) 

sapply(mydata, sd) 
## two-way contingency table of categorical outcomes and predictors 
## we want to make sure there are not 0 cells 

xtabs(~ admit + rank, data = mydata)
```

```{r}
mydata$rank <- factor(mydata$rank) 
mylogit <- glm(admit ~ gre + gpa + rank, data = mydata, family = "binomial")
summary(mylogit)
```

```{r}
## CIs using profiled log-likelihood 
confint(mylogit) 

## CIs using standard errors 
confint.default(mylogit)
```

```{r}
wald.test(b = coef(mylogit), Sigma = vcov(mylogit), Terms = 4:6)
```

```{r}
l <- cbind(0,0,0,1,-1,0) 
wald.test(b = coef(mylogit), Sigma = vcov(mylogit), L = l)
```

```{r}
## odds ratios only 
exp(coef(mylogit)) 

## odds ratios and 95% CI 
exp(cbind(OR = coef(mylogit), confint(mylogit)))
```

```{r}
newdata1 <- with(mydata, 
                 data.frame(gre = mean(gre), 
                            gpa = mean(gpa), 
                            rank = factor(1:4))) 
## view data frame 
newdata1
```

```{r}
newdata1$rankP <- predict(mylogit, newdata = newdata1, type = "response") 
newdata1
```

```{r}
newdata2 <- with(mydata, 
                 data.frame(gre = rep(seq(from = 200, to = 800, length.out = 100), 4), 
                            gpa = mean(gpa), 
                            rank = factor(rep(1:4, each = 100))))
```

```{r}
newdata3 <- cbind(newdata2, 
                  predict(mylogit, 
                          newdata = newdata2, 
                          type="link", 
                          se=TRUE)) 

newdata3 <- within(newdata3, { 
  PredictedProb <- plogis(fit) 
  LL <- plogis(fit - (1.96 * se.fit)) 
  UL <- plogis(fit + (1.96 * se.fit)) }) 

## view first few rows of final dataset 
head(newdata3)
```

```{r}
ggplot(newdata3, aes(x = gre, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = rank), alpha = .2) + 
  geom_line(aes(colour = rank), size=1)
```

```{r}
with(mylogit, null.deviance - deviance)
```

```{r}
with(mylogit, df.null - df.residual)
```

```{r}
with(mylogit,
     pchisq(null.deviance - deviance, 
            df.null - df.residual, 
            lower.tail = FALSE))
```

```{r}
logLik(mylogit)
```
