---
title: "code_for_discussion3"
author: "Jason Grahn"
date: "1/21/2019"
output: github_document
---

The instructor has us blindly running the code from https://blog.revolutionanalytics.com/2015/04/association-rules-and-market-basket-analysis-with-r.html witout any sort of explanation. 

So, I'm running it. But this is a better resource: http://www.rdatamining.com/examples/association-rules

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("~/da420_hw/project2/titanic.raw.rdata")

idx <- sample(1:nrow(titanic.raw), 5)

titanic.raw[idx, ]
summary(titanic.raw)
```

```{r}
 library(arules)
 # find association rules with default settings
rules <- apriori(titanic.raw)
inspect(rules)
```

```{r}
# rules with rhs containing "Survived" only
rules <- apriori(titanic.raw,
                 parameter = list(minlen=2, supp=0.005, conf=0.8),
                 appearance = list(rhs=c("Survived=No", "Survived=Yes"),
                                   default="lhs"),
                 control = list(verbose=F))
rules.sorted <- sort(rules, by="lift")
inspect(rules.sorted)
```

find redundant rules
```{r}
# find redundant rules
subset.matrix <- is.subset(rules.sorted, rules.sorted)
subset.matrix[lower.tri(subset.matrix, diag=T)] <- NA
redundant <- colSums(subset.matrix, na.rm=T) >= 1
```
 
which rules are redundant?
```{r}
which(redundant)

# remove redundant rules
rules.pruned <- rules.sorted[!redundant]
inspect(rules.pruned)
```

interpretation
```{r}
library(arulesViz)
plot(rules)
```

```{r}
plot(rules, method="graph", control=list(type="items"))
```

```{r}
plot(rules, method="paracoord", control=list(reorder=TRUE))
```

